### ISSUE TITLE
server does not start

### ISSUE THREAD

**Issue by koushyk** [Copephobia/BrowserQuest#1]
node server/js/main.js 
Could not open config file: ./server/config_local.json
internal/fs/utils.js:461
    throw err;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type undefined
    at Object.lstatSync (fs.js:857:3)
    at Class.init (/home/chasey/itechart/project_demo/BrowserQuest/server/js/map.js:14:13)
    at new Class (/home/chasey/itechart/project_demo/BrowserQuest/server/js/lib/class.js:50:23)
    at new Server (/home/chasey/itechart/project_demo/BrowserQuest/node_modules/socket.io/lib/index.js:51:21)
    at Server (/home/chasey/itechart/project_demo/BrowserQuest/node_modules/socket.io/lib/index.js:44:41)
    at Class.init (/home/chasey/itechart/project_demo/BrowserQuest/server/js/ws.js:110:39)
    at new Class (/home/chasey/itechart/project_demo/BrowserQuest/server/js/lib/class.js:50:23)
    at main (/home/chasey/itechart/project_demo/BrowserQuest/server/js/main.js:11:18)
    at /home/chasey/itechart/project_demo/BrowserQuest/server/js/main.js:136:13
    at ReadFileContext.callback (/home/chasey/itechart/project_demo/BrowserQuest/server/js/main.js:115:13)

**Comment by konijn** [comment]
Yeah, same here :/ But in 2021. The stack trace is super interesting switching between browserquest, socket.io and back.

**Comment by BalanceNetwork** [comment]
Any solution?
